
INSERT INTO tse.organization(org_id, last_updated_date_time, organization_display_name, organization_name, owner_account_id, created_date_time)
	VALUES (1,null,'Personal','Personal', null, CURRENT_TIMESTAMP(0)::timestamp);

INSERT INTO tse.bu(bu_id, org_id, bu_name, last_updated_date_time,created_date_time,owner_account_id)
	VALUES (0, 0, 'Default',CURRENT_TIMESTAMP(0)::timestamp,CURRENT_TIMESTAMP(0)::timestamp,NULL);

Insert into tse.country(country_id, country_name, created_date_time, last_updated_date_time) values
(1,'Afghanistan',CURRENT_TIMESTAMP(0)::timestamp,null),
(2,'Aland Islands (Finland)',CURRENT_TIMESTAMP(0)::timestamp,null),
(3,'Albania',CURRENT_TIMESTAMP(0)::timestamp,null),
(4,'Algeria',CURRENT_TIMESTAMP(0)::timestamp,null),
(5,'American Samoa (USA)',CURRENT_TIMESTAMP(0)::timestamp,null),
(6,'Andorra',CURRENT_TIMESTAMP(0)::timestamp,null),
(7,'Angola',CURRENT_TIMESTAMP(0)::timestamp,null),
(8,'Anguilla (UK)',CURRENT_TIMESTAMP(0)::timestamp,null),
(9,'Antigua and Barbuda',CURRENT_TIMESTAMP(0)::timestamp,null),
(10,'Argentina',CURRENT_TIMESTAMP(0)::timestamp,null),
(11,'Armenia',CURRENT_TIMESTAMP(0)::timestamp,null),
(12,'Aruba (Netherlands)',CURRENT_TIMESTAMP(0)::timestamp,null),
(13,'Australia',CURRENT_TIMESTAMP(0)::timestamp,null),
(14,'Austria',CURRENT_TIMESTAMP(0)::timestamp,null),
(15,'Azerbaijan',CURRENT_TIMESTAMP(0)::timestamp,null),
(16,'Bahamas',CURRENT_TIMESTAMP(0)::timestamp,null),
(17,'Bahrain',CURRENT_TIMESTAMP(0)::timestamp,null),
(18,'Bangladesh',CURRENT_TIMESTAMP(0)::timestamp,null),
(19,'Barbados',CURRENT_TIMESTAMP(0)::timestamp,null),
(20,'Belarus',CURRENT_TIMESTAMP(0)::timestamp,null),
(21,'Belgium',CURRENT_TIMESTAMP(0)::timestamp,null),
(22,'Belize',CURRENT_TIMESTAMP(0)::timestamp,null),
(23,'Benin',CURRENT_TIMESTAMP(0)::timestamp,null),
(24,'Bermuda (UK)',CURRENT_TIMESTAMP(0)::timestamp,null),
(25,'Bhutan',CURRENT_TIMESTAMP(0)::timestamp,null),
(26,'Bolivia',CURRENT_TIMESTAMP(0)::timestamp,null),
(27,'Bosnia and Herzegovina',CURRENT_TIMESTAMP(0)::timestamp,null),
(28,'Botswana',CURRENT_TIMESTAMP(0)::timestamp,null),
(29,'Brazil',CURRENT_TIMESTAMP(0)::timestamp,null),
(30,'British Virgin Islands (UK)',CURRENT_TIMESTAMP(0)::timestamp,null),
(31,'Brunei',CURRENT_TIMESTAMP(0)::timestamp,null),
(32,'Bulgaria',CURRENT_TIMESTAMP(0)::timestamp,null),
(33,'Burkina Faso',CURRENT_TIMESTAMP(0)::timestamp,null),
(34,'Burma',CURRENT_TIMESTAMP(0)::timestamp,null),
(35,'Burundi',CURRENT_TIMESTAMP(0)::timestamp,null),
(36,'Cambodia',CURRENT_TIMESTAMP(0)::timestamp,null),
(37,'Cameroon',CURRENT_TIMESTAMP(0)::timestamp,null),
(38,'Canada',CURRENT_TIMESTAMP(0)::timestamp,null),
(39,'Cape Verde',CURRENT_TIMESTAMP(0)::timestamp,null),
(40,'Caribbean Netherlands (Netherlands)',CURRENT_TIMESTAMP(0)::timestamp,null),
(41,'Cayman Islands (UK)',CURRENT_TIMESTAMP(0)::timestamp,null),
(42,'Central African Republic',CURRENT_TIMESTAMP(0)::timestamp,null),
(43,'Chad',CURRENT_TIMESTAMP(0)::timestamp,null),
(44,'Chile',CURRENT_TIMESTAMP(0)::timestamp,null),
(45,'China',CURRENT_TIMESTAMP(0)::timestamp,null),
(46,'Christmas Island (Australia)',CURRENT_TIMESTAMP(0)::timestamp,null),
(47,'Cocos (Keeling) Islands (Australia)',CURRENT_TIMESTAMP(0)::timestamp,null),
(48,'Colombia',CURRENT_TIMESTAMP(0)::timestamp,null),
(49,'Comoros',CURRENT_TIMESTAMP(0)::timestamp,null),
(50,'Cook Islands (NZ)',CURRENT_TIMESTAMP(0)::timestamp,null),
(51,'Costa Rica',CURRENT_TIMESTAMP(0)::timestamp,null),
(52,'Croatia',CURRENT_TIMESTAMP(0)::timestamp,null),
(53,'Cuba',CURRENT_TIMESTAMP(0)::timestamp,null),
(54,'Curacao (Netherlands)',CURRENT_TIMESTAMP(0)::timestamp,null),
(55,'Cyprus',CURRENT_TIMESTAMP(0)::timestamp,null),
(56,'Czech Republic',CURRENT_TIMESTAMP(0)::timestamp,null),
(57,'Democratic Republic of the Congo',CURRENT_TIMESTAMP(0)::timestamp,null),
(58,'Denmark',CURRENT_TIMESTAMP(0)::timestamp,null),
(59,'Djibouti',CURRENT_TIMESTAMP(0)::timestamp,null),
(60,'Dominica',CURRENT_TIMESTAMP(0)::timestamp,null),
(61,'Dominican Republic',CURRENT_TIMESTAMP(0)::timestamp,null),
(62,'Ecuador',CURRENT_TIMESTAMP(0)::timestamp,null),
(63,'Egypt',CURRENT_TIMESTAMP(0)::timestamp,null),
(64,'El Salvador',CURRENT_TIMESTAMP(0)::timestamp,null),
(65,'Equatorial Guinea',CURRENT_TIMESTAMP(0)::timestamp,null),
(66,'Eritrea',CURRENT_TIMESTAMP(0)::timestamp,null),
(67,'Estonia',CURRENT_TIMESTAMP(0)::timestamp,null),
(68,'Ethiopia',CURRENT_TIMESTAMP(0)::timestamp,null),
(69,'Falkland Islands (UK)',CURRENT_TIMESTAMP(0)::timestamp,null),
(70,'Faroe Islands (Denmark)',CURRENT_TIMESTAMP(0)::timestamp,null),
(71,'Federated States of Micronesia',CURRENT_TIMESTAMP(0)::timestamp,null),
(72,'Fiji',CURRENT_TIMESTAMP(0)::timestamp,null),
(73,'Finland',CURRENT_TIMESTAMP(0)::timestamp,null),
(74,'France',CURRENT_TIMESTAMP(0)::timestamp,null),
(75,'French Guiana (France)',CURRENT_TIMESTAMP(0)::timestamp,null),
(76,'French Polynesia (France)',CURRENT_TIMESTAMP(0)::timestamp,null),
(77,'Gabon',CURRENT_TIMESTAMP(0)::timestamp,null),
(78,'Gambia',CURRENT_TIMESTAMP(0)::timestamp,null),
(79,'Georgia',CURRENT_TIMESTAMP(0)::timestamp,null),
(80,'Germany',CURRENT_TIMESTAMP(0)::timestamp,null),
(81,'Ghana',CURRENT_TIMESTAMP(0)::timestamp,null),
(82,'Gibraltar (UK)',CURRENT_TIMESTAMP(0)::timestamp,null),
(83,'Greece',CURRENT_TIMESTAMP(0)::timestamp,null),
(84,'Greenland (Denmark)',CURRENT_TIMESTAMP(0)::timestamp,null),
(85,'Grenada',CURRENT_TIMESTAMP(0)::timestamp,null),
(86,'Guadeloupe (France)',CURRENT_TIMESTAMP(0)::timestamp,null),
(87,'Guam (USA)',CURRENT_TIMESTAMP(0)::timestamp,null),
(88,'Guatemala',CURRENT_TIMESTAMP(0)::timestamp,null),
(89,'Guernsey (UK)',CURRENT_TIMESTAMP(0)::timestamp,null),
(90,'Guinea',CURRENT_TIMESTAMP(0)::timestamp,null),
(91,'Guinea-Bissau',CURRENT_TIMESTAMP(0)::timestamp,null),
(92,'Guyana',CURRENT_TIMESTAMP(0)::timestamp,null),
(93,'Haiti',CURRENT_TIMESTAMP(0)::timestamp,null),
(94,'Honduras',CURRENT_TIMESTAMP(0)::timestamp,null),
(95,'Hong Kong (China)',CURRENT_TIMESTAMP(0)::timestamp,null),
(96,'Hungary',CURRENT_TIMESTAMP(0)::timestamp,null),
(97,'Iceland',CURRENT_TIMESTAMP(0)::timestamp,null),
(98,'India',CURRENT_TIMESTAMP(0)::timestamp,null),
(99,'Indonesia',CURRENT_TIMESTAMP(0)::timestamp,null),
(100,'Iran',CURRENT_TIMESTAMP(0)::timestamp,null),
(101,'Iraq',CURRENT_TIMESTAMP(0)::timestamp,null),
(102,'Ireland',CURRENT_TIMESTAMP(0)::timestamp,null),
(103,'Isle of Man (UK)',CURRENT_TIMESTAMP(0)::timestamp,null),
(104,'Israel',CURRENT_TIMESTAMP(0)::timestamp,null),
(105,'Italy',CURRENT_TIMESTAMP(0)::timestamp,null),
(106,'Ivory Coast',CURRENT_TIMESTAMP(0)::timestamp,null),
(107,'Jamaica',CURRENT_TIMESTAMP(0)::timestamp,null),
(108,'Japan',CURRENT_TIMESTAMP(0)::timestamp,null),
(109,'Jersey (UK)',CURRENT_TIMESTAMP(0)::timestamp,null),
(110,'Jordan',CURRENT_TIMESTAMP(0)::timestamp,null),
(111,'Kazakhstan',CURRENT_TIMESTAMP(0)::timestamp,null),
(112,'Kenya',CURRENT_TIMESTAMP(0)::timestamp,null),
(113,'Kiribati',CURRENT_TIMESTAMP(0)::timestamp,null),
(114,'Kosovo',CURRENT_TIMESTAMP(0)::timestamp,null),
(115,'Kuwait',CURRENT_TIMESTAMP(0)::timestamp,null),
(116,'Kyrgyzstan',CURRENT_TIMESTAMP(0)::timestamp,null),
(117,'Laos',CURRENT_TIMESTAMP(0)::timestamp,null),
(118,'Latvia',CURRENT_TIMESTAMP(0)::timestamp,null),
(119,'Lebanon',CURRENT_TIMESTAMP(0)::timestamp,null),
(120,'Lesotho',CURRENT_TIMESTAMP(0)::timestamp,null),
(121,'Liberia',CURRENT_TIMESTAMP(0)::timestamp,null),
(122,'Libya',CURRENT_TIMESTAMP(0)::timestamp,null),
(123,'Liechtenstein',CURRENT_TIMESTAMP(0)::timestamp,null),
(124,'Lithuania',CURRENT_TIMESTAMP(0)::timestamp,null),
(125,'Luxembourg',CURRENT_TIMESTAMP(0)::timestamp,null),
(126,'Macau (China)',CURRENT_TIMESTAMP(0)::timestamp,null),
(127,'Macedonia',CURRENT_TIMESTAMP(0)::timestamp,null),
(128,'Madagascar',CURRENT_TIMESTAMP(0)::timestamp,null),
(129,'Malawi',CURRENT_TIMESTAMP(0)::timestamp,null),
(130,'Malaysia',CURRENT_TIMESTAMP(0)::timestamp,null),
(131,'Maldives',CURRENT_TIMESTAMP(0)::timestamp,null),
(132,'Mali',CURRENT_TIMESTAMP(0)::timestamp,null),
(133,'Malta',CURRENT_TIMESTAMP(0)::timestamp,null),
(134,'Marshall Islands',CURRENT_TIMESTAMP(0)::timestamp,null),
(135,'Martinique (France)',CURRENT_TIMESTAMP(0)::timestamp,null),
(136,'Mauritania',CURRENT_TIMESTAMP(0)::timestamp,null),
(137,'Mauritius',CURRENT_TIMESTAMP(0)::timestamp,null),
(138,'Mayotte (France)',CURRENT_TIMESTAMP(0)::timestamp,null),
(139,'Mexico',CURRENT_TIMESTAMP(0)::timestamp,null),
(140,'Moldov',CURRENT_TIMESTAMP(0)::timestamp,null),
(141,'Monaco',CURRENT_TIMESTAMP(0)::timestamp,null),
(142,'Mongolia',CURRENT_TIMESTAMP(0)::timestamp,null),
(143,'Montenegro',CURRENT_TIMESTAMP(0)::timestamp,null),
(144,'Montserrat (UK)',CURRENT_TIMESTAMP(0)::timestamp,null),
(145,'Morocco',CURRENT_TIMESTAMP(0)::timestamp,null),
(146,'Mozambique',CURRENT_TIMESTAMP(0)::timestamp,null),
(147,'Namibia',CURRENT_TIMESTAMP(0)::timestamp,null),
(148,'Nauru',CURRENT_TIMESTAMP(0)::timestamp,null),
(149,'Nepal',CURRENT_TIMESTAMP(0)::timestamp,null),
(150,'Netherlands',CURRENT_TIMESTAMP(0)::timestamp,null),
(151,'New Caledonia (France)',CURRENT_TIMESTAMP(0)::timestamp,null),
(152,'New Zealand',CURRENT_TIMESTAMP(0)::timestamp,null),
(153,'Nicaragua',CURRENT_TIMESTAMP(0)::timestamp,null),
(154,'Niger',CURRENT_TIMESTAMP(0)::timestamp,null),
(155,'Nigeria',CURRENT_TIMESTAMP(0)::timestamp,null),
(156,'Niue (NZ)',CURRENT_TIMESTAMP(0)::timestamp,null),
(157,'Norfolk Island (Australia)',CURRENT_TIMESTAMP(0)::timestamp,null),
(158,'North Korea',CURRENT_TIMESTAMP(0)::timestamp,null),
(159,'Northern Mariana Islands (USA)',CURRENT_TIMESTAMP(0)::timestamp,null),
(160,'Norway',CURRENT_TIMESTAMP(0)::timestamp,null),
(161,'Oman',CURRENT_TIMESTAMP(0)::timestamp,null),
(162,'Pakistan',CURRENT_TIMESTAMP(0)::timestamp,null),
(163,'Palau',CURRENT_TIMESTAMP(0)::timestamp,null),
(164,'Palestine',CURRENT_TIMESTAMP(0)::timestamp,null),
(165,'Panama',CURRENT_TIMESTAMP(0)::timestamp,null),
(166,'Papua New Guinea',CURRENT_TIMESTAMP(0)::timestamp,null),
(167,'Paraguay',CURRENT_TIMESTAMP(0)::timestamp,null),
(168,'Peru',CURRENT_TIMESTAMP(0)::timestamp,null),
(169,'Philippines',CURRENT_TIMESTAMP(0)::timestamp,null),
(170,'Pitcairn Islands (UK)',CURRENT_TIMESTAMP(0)::timestamp,null),
(171,'Poland',CURRENT_TIMESTAMP(0)::timestamp,null),
(172,'Portugal',CURRENT_TIMESTAMP(0)::timestamp,null),
(173,'Puerto Rico',CURRENT_TIMESTAMP(0)::timestamp,null),
(174,'Qatar',CURRENT_TIMESTAMP(0)::timestamp,null),
(175,'Republic of the Congo',CURRENT_TIMESTAMP(0)::timestamp,null),
(176,'Reunion (France)',CURRENT_TIMESTAMP(0)::timestamp,null),
(177,'Romania',CURRENT_TIMESTAMP(0)::timestamp,null),
(178,'Russia',CURRENT_TIMESTAMP(0)::timestamp,null),
(179,'Rwanda',CURRENT_TIMESTAMP(0)::timestamp,null),
(180,'Saint Barthelemy (France)',CURRENT_TIMESTAMP(0)::timestamp,null),
(181,'Saint Helena, Ascension and Tristan da Cunha (UK)',CURRENT_TIMESTAMP(0)::timestamp,null),
(182,'Saint Kitts and Nevis',CURRENT_TIMESTAMP(0)::timestamp,null),
(183,'Saint Lucia',CURRENT_TIMESTAMP(0)::timestamp,null),
(184,'Saint Martin (France)',CURRENT_TIMESTAMP(0)::timestamp,null),
(185,'Saint Pierre and Miquelon (France)',CURRENT_TIMESTAMP(0)::timestamp,null),
(186,'Saint Vincent and the Grenadines',CURRENT_TIMESTAMP(0)::timestamp,null),
(187,'Samoa',CURRENT_TIMESTAMP(0)::timestamp,null),
(188,'San Marino',CURRENT_TIMESTAMP(0)::timestamp,null),
(189,'Sao Tom and Principe',CURRENT_TIMESTAMP(0)::timestamp,null),
(190,'Saudi Arabia',CURRENT_TIMESTAMP(0)::timestamp,null),
(191,'Senegal',CURRENT_TIMESTAMP(0)::timestamp,null),
(192,'Serbia',CURRENT_TIMESTAMP(0)::timestamp,null),
(193,'Seychelles',CURRENT_TIMESTAMP(0)::timestamp,null),
(194,'Sierra Leone',CURRENT_TIMESTAMP(0)::timestamp,null),
(195,'Singapore',CURRENT_TIMESTAMP(0)::timestamp,null),
(196,'Sint Maarten (Netherlands)',CURRENT_TIMESTAMP(0)::timestamp,null),
(197,'Slovakia',CURRENT_TIMESTAMP(0)::timestamp,null),
(198,'Slovenia',CURRENT_TIMESTAMP(0)::timestamp,null),
(199,'Solomon Islands',CURRENT_TIMESTAMP(0)::timestamp,null),
(200,'Somalia',CURRENT_TIMESTAMP(0)::timestamp,null),
(201,'South Africa',CURRENT_TIMESTAMP(0)::timestamp,null),
(202,'South Korea',CURRENT_TIMESTAMP(0)::timestamp,null),
(203,'South Sudan',CURRENT_TIMESTAMP(0)::timestamp,null),
(204,'Spain',CURRENT_TIMESTAMP(0)::timestamp,null),
(205,'Sri Lanka',CURRENT_TIMESTAMP(0)::timestamp,null),
(206,'Sudan',CURRENT_TIMESTAMP(0)::timestamp,null),
(207,'Suriname',CURRENT_TIMESTAMP(0)::timestamp,null),
(208,'Svalbard and Jan Mayen (Norway)',CURRENT_TIMESTAMP(0)::timestamp,null),
(209,'Swaziland',CURRENT_TIMESTAMP(0)::timestamp,null),
(210,'Sweden',CURRENT_TIMESTAMP(0)::timestamp,null),
(211,'Switzerland',CURRENT_TIMESTAMP(0)::timestamp,null),
(212,'Syria',CURRENT_TIMESTAMP(0)::timestamp,null),
(213,'Taiwan',CURRENT_TIMESTAMP(0)::timestamp,null),
(214,'Tajikistan',CURRENT_TIMESTAMP(0)::timestamp,null),
(215,'Tanzania',CURRENT_TIMESTAMP(0)::timestamp,null),
(216,'Thailand',CURRENT_TIMESTAMP(0)::timestamp,null),
(217,'Timor-Leste',CURRENT_TIMESTAMP(0)::timestamp,null),
(218,'Togo',CURRENT_TIMESTAMP(0)::timestamp,null),
(219,'Tokelau (NZ)',CURRENT_TIMESTAMP(0)::timestamp,null),
(220,'Tonga',CURRENT_TIMESTAMP(0)::timestamp,null),
(221,'Trinidad and Tobago',CURRENT_TIMESTAMP(0)::timestamp,null),
(222,'Tunisia',CURRENT_TIMESTAMP(0)::timestamp,null),
(223,'Turkey',CURRENT_TIMESTAMP(0)::timestamp,null),
(224,'Turkmenistan',CURRENT_TIMESTAMP(0)::timestamp,null),
(225,'Turks and Caicos Islands (UK)',CURRENT_TIMESTAMP(0)::timestamp,null),
(226,'Tuvalu',CURRENT_TIMESTAMP(0)::timestamp,null),
(227,'Uganda',CURRENT_TIMESTAMP(0)::timestamp,null),
(228,'Ukraine',CURRENT_TIMESTAMP(0)::timestamp,null),
(229,'United Arab Emirates',CURRENT_TIMESTAMP(0)::timestamp,null),
(230,'United Kingdom',CURRENT_TIMESTAMP(0)::timestamp,null),
(231,'United States',CURRENT_TIMESTAMP(0)::timestamp,null),
(232,'United States Virgin Islands (USA)',CURRENT_TIMESTAMP(0)::timestamp,null),
(233,'Uruguay',CURRENT_TIMESTAMP(0)::timestamp,null),
(234,'Uzbekistan',CURRENT_TIMESTAMP(0)::timestamp,null),
(235,'Vanuatu',CURRENT_TIMESTAMP(0)::timestamp,null),
(236,'Vatican City',CURRENT_TIMESTAMP(0)::timestamp,null),
(237,'Venezuela',CURRENT_TIMESTAMP(0)::timestamp,null),
(238,'Vietnam',CURRENT_TIMESTAMP(0)::timestamp,null),
(239,'Wallis and Futuna (France)',CURRENT_TIMESTAMP(0)::timestamp,null),
(240,'Western Sahara',CURRENT_TIMESTAMP(0)::timestamp,null),
(241,'Yemen',CURRENT_TIMESTAMP(0)::timestamp,null),
(242,'Zambia',CURRENT_TIMESTAMP(0)::timestamp,null),
(243,'Zimbabwe',CURRENT_TIMESTAMP(0)::timestamp,null)
;

INSERT INTO tse.education(education_id, education_description, education_display_name, created_date_time, last_updated_date_time)
	VALUES (1,'Middle School', 'Middle School', CURRENT_TIMESTAMP(0)::timestamp, null),
        (2, 'High School', 'High School', CURRENT_TIMESTAMP(0)::timestamp, null),
		(3,'Undergraduate/College', 'Undergraduate/College', CURRENT_TIMESTAMP(0)::timestamp, null),
        (4, 'Post Graduate/Masters', 'Post Graduate/Masters', CURRENT_TIMESTAMP(0)::timestamp, null),
		(5,'MBA', 'MBA', CURRENT_TIMESTAMP(0)::timestamp, null),
        (6, 'JD', 'JD', CURRENT_TIMESTAMP(0)::timestamp, null),
		(7,'Medical Doctor', 'Medical Doctor', CURRENT_TIMESTAMP(0)::timestamp, null),
        (8, 'PhD', 'PhD', CURRENT_TIMESTAMP(0)::timestamp, null)
        ;





INSERT INTO tse.age_range(
	age_range_id, age_range_description, age_range_display_name, created_date_time, last_updated_date_time)
	VALUES (1,'12-15', '12-15', CURRENT_TIMESTAMP(0)::timestamp, null),
        (2, '16-18', '16-18', CURRENT_TIMESTAMP(0)::timestamp, null),
		(3,'19-22', '19-22', CURRENT_TIMESTAMP(0)::timestamp, null),
        (4, '23-26', '23-26', CURRENT_TIMESTAMP(0)::timestamp, null),
		(5,'27-34', '27-34', CURRENT_TIMESTAMP(0)::timestamp, null),
        (6, '35-44', '35-44', CURRENT_TIMESTAMP(0)::timestamp, null),
		(7,'45-54', '45-54', CURRENT_TIMESTAMP(0)::timestamp, null),
        (8, '55-64', '55-64', CURRENT_TIMESTAMP(0)::timestamp, null),
        (9, '65 or older', '65 or older', CURRENT_TIMESTAMP(0)::timestamp, null)
        ;




INSERT INTO tse.gender(gender_id, gender_description, gender_display_name, created_date_time, last_updated_date_time)
        VALUES (1, 'Female', 'Female', CURRENT_TIMESTAMP(0)::timestamp, null),
				(2,'Male', 'Male', CURRENT_TIMESTAMP(0)::timestamp, null),
				(8, 'Do not wish to specify', 'Do not wish to specify', CURRENT_TIMESTAMP(0)::timestamp, null),
				(9, 'Other', 'Other', CURRENT_TIMESTAMP(0)::timestamp, null)
	;



INSERT INTO tse.project
(project_id, org_id, project_name, bu_id, created_date_time, last_updated_date_time, owner_account_id)
VALUES(1, 1, 'Data Project', 1, '2022-10-02 00:00:00.000', '2022-10-02 00:00:00.000', 1);


INSERT INTO tse.tse_users
(user_id, age_range, alternate_email, city, created_date_time, current_org_email, first_name, gender, given_name, highest_education, is_alternate_email_personal, is_primary_email_personal, last_name, last_updated_date_time, locale, middle_name, multi_association, personal_email, primary_email, second_highest_education, time_zone, country_id)
VALUES(2, 1, NULL, NULL, '2022-10-27 19:56:39.779', NULL, 'Karan', 1, NULL, 1, NULL, true, 'Chutani', NULL, NULL, NULL, false, '1802karank2@gmail.com', '1802karank2@gmail.com', NULL, 'Asia/Calcutta', 1);


INSERT INTO tse.user_account
(account_id, created_date_time, email, is_active, is_default, last_updated_date_time, org_id, user_id)
VALUES(1, '2022-10-27 19:56:39.825', '1802karank2@gmail.com', true, NULL, NULL, 1, 2);
