package com.tse.core_application.constants;


public enum NotificationTypeToCategory {

    CREATE_TASK("CREATE_TASK", 8),
    UPDATE_TASK_ESTIMATE("UPDATE_TASK_ESTIMATE", 6),
    UPDATE_TASK_SCHEDULE("UPDATE_TASK_SCHEDULE", 6),
    UPDATE_TASK_PROGRESS("UPDATE_TASK_PROGRESS", 7),
    UPDATE_TASK_TITLE("UPDATE_TASK_TITLE", 6),
    UPDATE_TASK_DESC("UPDATE_TASK_DESC", 6),
    UPDATE_TASK_EFFORT("UPDATE_TASK_EFFORT", 14),
    TASK_GETTING_DELAYED("TASK_GETTING_DELAYED", 7),
    TASK_GETTING_WATCHLISTED("TASK_GETTING_WATCHLISTED", 7),
    UPDATE_TASK_CURR_ACTIVITY_IND("UPDATE_TASK_CURR_ACTIVITY_IND", 7),
    UPDATE_TASK_CURR_SCHEDULED_TASK_IND("UPDATE_TASK_CURR_SCHEDULED_TASK_IND", 7),
    UPDATE_TASK_RECORD_VOICE_STATUS("UPDATE_TASK_RECORD_VOICE_STATUS", 7),
    UPDATE_TASK_IN_BACKLOG("UPDATE_TASK_IN_BACKLOG", 9),
    UPDATE_TASK_STAKEHOLDERS("UPDATE_TASK_STAKEHOLDERS", 9),
    UPDATE_TASK_PRIORITY("UPDATE_TASK_PRIORITY", 9),
    UPDATE_TASK_ASSIGNMENT("UPDATE_TASK_ASSIGNMENT", 9),
    UPDATE_TASK_COMMENTS("UPDATE_TASK_COMMENTS", 9),
    UPDATE_TASK_NOTES("UPDATE_TASK_NOTES", 9),
    UPDATE_TASK_OTHER_ACTIVITIES("UPDATE_TASK_OTHER_ACTIVITIES", 9),
    MEETING_INVITE("MEETING_INVITE", 2),
    MEETING_UPDATE("MEETING_UPDATE", 2),
    MEETING_FOLLOW_UP("MEETING_FOLLOW_UP", 3),
    START_MEETING_CONFIRMATION("START_MEETING_CONFIRMATION", 3),
    END_MEETING_CONFIRMATION("END_MEETING_CONFIRMATION", 3),
    TIMESHEET_REMINDER("TIMESHEET_REMINDER", 4),
    MEETING_REMINDER("MEETING_REMINDER", 4),
    GROUP_MESSAGE("GROUP_MESSAGE", 5),
    IMMEDIATE_ATTENTION("IMMEDIATE_ATTENTION", 1),
    NEW_ACCESS_DOMAIN("NEW_ACCESS_DOMAIN", 10),
    UPDATED_ACCESS_DOMAIN("UPDATED_ACCESS_DOMAIN", 10),
    UPDATED_USER_NAME("UPDATED_USER_NAME", 10),
    LEAVE_APPROVAL("LEAVE_APPROVAL", 11),
    LEAVE_CANCELLED("LEAVE_CANCELLED", 11),
    LEAVE_REJECTED("LEAVE_REJECTED", 11),
    LEAVE_APPLIED("LEAVE_APPLIED", 11),
    LEAVE_UPDATED("LEAVE_UPDATED", 11),
    OTHERS("OTHERS", 12),
    MENTION_ALERTS_GC("MENTION_ALERTS_GC", 13),
    MENTION_ALERTS_TC("MENTION_ALERTS_TC", 13),
    EFFORT_ALERTS("EFFORT_ALERTS", 14),
    USER_PREFERENCE_UPDATE("USER_PREFERENCE_UPDATE", 15),
    USER_REMOVE_UPDATE("USER_REMOVE_UPDATE", 15),
    TEMPLATE_UPDATE("TEMPLATE_UPDATE", 16),
    STATUS_INQUIRY("STATUS_INQUIRY", 17),
    LEAVE_EXPIRED("LEAVE_EXPIRED", 11),
    // Claude change: PT-14409 - Added notification types for consumed leave edit/delete by Org Admin
    LEAVE_EDITED_BY_ADMIN("LEAVE_EDITED_BY_ADMIN", 11),
    LEAVE_DELETED_BY_ADMIN("LEAVE_DELETED_BY_ADMIN", 11),
    COMMENT("COMMENT",18),
    NOTE("NOTE",19),
    EPIC_STARTED("EPIC_STARTED", 20),
    SILENT_UPDATES("SILENT_UPDATES", 15),
    CONVERSATION("CONVERSATION", 5),
    IMPORT_JIRA("IMPORT_JIRA", 12),
    JIRA_INVITE_DECLINE("JIRA_INVITE_DECLINE", 12),
    USER_REMINDER("USER_REMINDER", 4),
    // ---- remove these and check the notification type table  --- //
    UPDATE_TASK_KEY_DECISIONS("UPDATE_TASK_KEY_DECISIONS", 9),
    UPDATE_TASK_TIMESHEET("UPDATE_TASK_TIMESHEET", 9),
    MEETING_ANALYSIS("MEETING_ANALYSIS", 2),
    FLAGGED_UNFLAGGED_NOTIFICATION("FLAGGED_UNFLAGGED_NOTIFICATION",9);
    // ------------------------------------------------------------//
    private final String notificationType;
    private final int categoryId;

    NotificationTypeToCategory(String notificationType, int categoryId) {
        this.notificationType = notificationType;
        this.categoryId = categoryId;
    }

    public String getNotificationType() {
        return notificationType;
    }

    public int getCategoryId() {
        return categoryId;
    }

    public static int getCategoryIdByNotificationType(String notificationType) {
        for (NotificationTypeToCategory entry : values()) {
            if (entry.getNotificationType().equals(notificationType)) {
                return entry.getCategoryId();
            }
        }
        return -1; // or any other default/error value
    }
}

